### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by gwleclerc** [Thiht/smocker#27]
Currently Smocker can work as a http proxy if you try to call an API using http_proxy variable. The call will be redirected to Smocker.

You can test this by:
- starting Smocker:
```bash
make start
```
- making a call using Smocker as http proxy
```bash
export http_proxy=http://localhost:8080/
curl -v http://jsonplaceholder.typicode.com/todos/1
```

Then you should see the call on Smocker.

But when we try to make a call using HTTPS and HTTPS_PROXY, the http client send a CONNECT request on the proxy server which is not handled correctly by Smocker.
It will respond to the call with a "No mock found matching the request" which will cancel the https request on client side.

**Comment by gwleclerc** [comment]
Currently we do not use Smocker behind HTTPS or as an HTTPS_PROXY. So if you miss this feature we are ready to try to implement it but we would need help with a real use case.

**Comment by Flow86** [comment]
Probably won't work, since the proxy is only tunneling the https connection. It cannot look into the requests itself. Even if it would be cool to run smocker on https itself. (Even if it needs a proper SSL certificate itself then

**Comment by Thiht** [comment]
we could bundle Smocker with self signed certificates and optionally allow to start it with TLS enabled. If we do this it will be easy to replace the self signed certs with valid certs by just overriding them

**Comment by iJebus** [comment]
I'd like to be able to do this just so as to more accurately represent a production service that uses TLS. Currently I have the `https://` hard-coded, although I guess I could strip out and make it part of config, just to make this mocking easier.

**Comment by comerford** [comment]
> we could bundle Smocker with self signed certificates and optionally allow to start it with TLS enabled. If we do this it will be easy to replace the self signed certs with valid certs by just overriding them

I think this is perfectly reasonable, once the capability is there, expecting people to bring their own certs is pretty standard for TLS

**Comment by ahahn95** [comment]
Would love it if smocker supported HTTPS!

**Comment by astrieanna** [comment]
I wanted to use Smocker to mock a service during tests, but my production code will only make requests to this service over HTTPS, so I don't feel comfortable using a mock on HTTP. I could easily provide certs when running Smocker (as I already do for other local versions of services I run during tests).

**Comment by Thiht** [comment]
Hi! 
I just tagged a [`tls-preview`](https://hub.docker.com/layers/thiht/smocker/tls-preview/images/sha256-e49aa1850026bdbfb2863db1050eea22aabb0f1c09f936a82496dd3dc7ab9d96?context=explore) Docker image if you want to give it a try.

I finally chose to not embed a default certificate at all, mainly because I don't know the good practice on this subject. If you want a certificate, even a self signed, you have to bring your own.

The staging doc is available here:

- [Installation](https://deploy-preview-239--smocker.netlify.app/guide/installation.html)
- [Arguments](https://deploy-preview-239--smocker.netlify.app/technical-documentation/arguments.html)

I just want to test it more thoroughly (I just tried to launch the binary with a self signed cert and that's it) before making a new release but it shouldn't be long. I'm taking feedbacks if something doesn't work correctly.

**Comment by gwleclerc** [comment]
Can you write how to test it with mkcert in the readme ? I'm curious about it.
